-- AlterTable
ALTER TABLE "BookStats" ADD COLUMN     "character_score" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "grammar_score" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "overall_score" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "story_score" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "style_score" DOUBLE PRECISION NOT NULL DEFAULT 0;
